/* Taj Al Molook V15 — Developer Control Center hotfix */
(function(){
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 let sb=null,profile=null,mode='developer';
 const client=()=>sb||(sb=window.supabase.createClient(window.TAJ_SUPABASE_URL,window.TAJ_SUPABASE_KEY));
 const toast=x=>window.showToast?window.showToast(x):alert(x);
 async function me(){const {data:{user}}=await client().auth.getUser();if(!user)return null;const {data,error}=await client().from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;return data}
 async function init(){try{profile=await me();const ok=profile&&String(profile.role||'').toLowerCase()==='developer'&&Number(profile.user_number)===1;if(!ok){cleanup();return}document.documentElement.classList.add('is-developer');ensureSwitch();const saved=localStorage.getItem('taj_dev_mode'); saved==='user'?enterUserPreview(false):await openDeveloper()}catch(e){console.warn(e);toast('تعذر تحميل صلاحية المطور: '+e.message)}}
 function cleanup(){document.documentElement.classList.remove('is-developer');document.body.classList.remove('developer-preview');$('devModeSwitch')?.remove();$('developerCenter')?.remove()}
 function ensureSwitch(){let d=$('devModeSwitch');if(!d){d=document.createElement('div');d.id='devModeSwitch';d.className='dev-mode-switch';d.innerHTML='<button type="button" data-mode="developer">👑 المطور <small>ID 1</small></button><button type="button" data-mode="user">👤 المستخدم <small>ID 100</small></button>';document.body.appendChild(d)}setSwitch()}
 function setSwitch(){document.body.classList.toggle('developer-preview',mode==='user');$('devModeSwitch')?.querySelector('[data-mode="developer"]')?.classList.toggle('active',mode==='developer');$('devModeSwitch')?.querySelector('[data-mode="user"]')?.classList.toggle('active',mode==='user')}
 async function switchMode(m){mode=m==='user'?'user':'developer';localStorage.setItem('taj_dev_mode',mode);setSwitch();if(mode==='user')enterUserPreview(true);else await openDeveloper()}
 function setPreviewId(on){document.body.dataset.previewId=on?'100':'';document.querySelectorAll('#guestBadge .member-text small').forEach(x=>x.textContent=on?'ID: 100':'ID: 1')}
 function enterUserPreview(notify=true){mode='user';setSwitch();$('developerCenter')?.remove();setPreviewId(true);try{window.openSection?.('home')}catch{}if(notify)toast('👤 معاينة المستخدم — ID 100')}
 async function openDeveloper(){mode='developer';ensureSwitch();setSwitch();setPreviewId(false);let root=$('developerCenter');if(!root){root=document.createElement('div');root.id='developerCenter';root.className='developer-center';document.body.appendChild(root)}root.innerHTML='<div class="dev-loading">👑 جاري تحميل لوحة المطور…</div>';await render(root)}
 async function q(table,select='*',order){let x=client().from(table).select(select);if(order)x=x.order(order,{ascending:false});const r=await x.limit(200);return r.error?{data:[],error:r.error}:r}
 async function render(root){const [u,co,sec,apps]=await Promise.all([q('profiles','id,user_number,display_name,points,role'),q('subscription_codes','*','created_at'),q('platform_sections','*'),q('platform_content','*','created_at')]);
  const users=u.data||[],codes=co.data||[],sections=sec.data?.length?sec.data:defaultSections(),content=apps.data||[];window.__devData={users,codes,sections,content};
  root.innerHTML=`<div class="dev-shell"><header><div><b>👑 مركز تحكم تاج الملوك</b><small>Developer • ID 1</small></div><div class="dev-head-actions"><button type="button" data-action="preview">👤 معاينة المستخدم</button><button type="button" data-action="refresh">↻ تحديث</button></div></header><div class="dev-stats"><span><b>${users.length}</b> حساب</span><span><b>${codes.length}</b> كود</span><span><b>${content.length}</b> منشور</span><span><b>${sections.filter(x=>x.enabled!==false).length}</b> قسم مفتوح</span></div><nav class="dev-tabs"><button data-tab="overview">⌂ الرئيسية</button><button data-tab="codes">🔑 الأكواد</button><button data-tab="users">👥 الحسابات</button><button data-tab="sections">⚙ الأقسام</button><button data-tab="publish">🚀 النشر</button></nav><main id="devPanel"></main></div>`;
  tab('overview'); if(u.error||co.error||sec.error||apps.error) toast('ملاحظة: بعض جداول لوحة المطور تحتاج تشغيل ملف SQL V15')}
 function defaultSections(){return ['home','buy-code','activate-code','download-store','apps','games','cloud-games','links','emulators','paid-games','settings'].map((k,i)=>({section_key:k,title:k,enabled:true,sort_order:i}))}
 function tab(t){const p=$('devPanel'),d=window.__devData;if(!p||!d)return;document.querySelectorAll('.dev-tabs [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));
  if(t==='overview')p.innerHTML='<section class="dev-hero"><h2>التحكم الكامل بالمنصة</h2><p>اختر أحد الأقسام بالأعلى لإدارة المنصة.</p></section>';
  if(t==='codes')p.innerHTML=`<section class="dev-card"><h3>إنشاء كود</h3><div class="dev-form"><select id="dcType"><option value="trial">تجريبي</option><option value="basic">أساسي</option></select><input id="dcMinutes" type="number" value="60" min="1"><button type="button" data-action="create-code">＋ إنشاء</button></div></section><section class="dev-card"><h3>الأكواد</h3>${d.codes.map(x=>`<div class="dev-row"><span><b>${esc(x.code)}</b><small>${esc(x.code_type)} • ${x.duration_minutes||0} دقيقة</small></span><em>${x.used_by?'مستخدم':'متاح'}</em></div>`).join('')||'<p>لا توجد أكواد</p>'}</section>`;
  if(t==='users')p.innerHTML=`<section class="dev-card"><h3>الحسابات</h3>${d.users.map(x=>`<div class="dev-row"><span><b>${esc(x.display_name||'حساب')}</b><small>ID ${esc(x.user_number)} • ${Number(x.points||0).toLocaleString()} نقطة</small></span><div>${Number(x.user_number)===1?'<em>المطور</em>':`<button data-user="${x.id}" data-status="banned">حظر</button><button data-user="${x.id}" data-status="active">فتح</button>`}</div></div>`).join('')}</section>`;
  if(t==='sections')p.innerHTML=`<section class="dev-card"><h3>فتح وقفل الأقسام</h3><p class="dev-note">القسم المقفول يظهر للمستخدم تحت الصيانة.</p>${d.sections.map(x=>`<label class="dev-row dev-toggle"><span><b>${esc(x.title||x.section_key)}</b><small>${esc(x.section_key)}</small></span><input type="checkbox" data-section="${esc(x.section_key)}" ${x.enabled!==false?'checked':''}></label>`).join('')}</section>`;
  if(t==='publish')p.innerHTML=`<section class="dev-card"><h3>نشر برنامج أو لعبة</h3><div class="dev-form publish"><input id="pubName" placeholder="الاسم"><input id="pubVersion" placeholder="الإصدار"><select id="pubType"><option value="app">تطبيق</option><option value="game">لعبة</option></select><input id="pubImage" placeholder="رابط الصورة"><input id="pubUrl" placeholder="رابط الملف"><textarea id="pubDesc" placeholder="الوصف"></textarea><button type="button" data-action="publish">🚀 نشر الآن</button></div></section><section class="dev-card"><h3>المنشورات</h3>${d.content.map(x=>`<div class="dev-row"><span><b>${esc(x.name)}</b><small>${esc(x.content_type)} • ${esc(x.version||'')}</small></span><button data-remove="${x.id}">حذف</button></div>`).join('')||'<p>لا توجد منشورات</p>'}</section>`}
 async function createCode(){const type=$('dcType')?.value,min=+$('dcMinutes')?.value||60;const r=await client().rpc('admin_create_code',{p_type:type,p_duration_minutes:min});if(r.error)return toast(r.error.message);toast('تم إنشاء الكود: '+r.data);await openDeveloper();tab('codes')}
 async function section(key,enabled){const {error}=await client().from('platform_sections').upsert({section_key:key,title:key,enabled,updated_at:new Date().toISOString()},{onConflict:'section_key'});if(error)return toast(error.message);toast(enabled?'تم فتح القسم':'تم وضع القسم تحت الصيانة')}
 async function setStatus(id,status){let r=await client().rpc('admin_set_account_status',{p_user:id,p_status:status});if(r.error&&window.tajV5?.setStatus)return window.tajV5.setStatus(id,status);if(r.error)return toast(r.error.message);toast('تم تحديث الحساب');await openDeveloper();tab('users')}
 async function publish(){const row={name:$('pubName')?.value.trim(),version:$('pubVersion')?.value.trim(),content_type:$('pubType')?.value,image_url:$('pubImage')?.value.trim(),download_url:$('pubUrl')?.value.trim(),description:$('pubDesc')?.value.trim(),published:true};if(!row.name)return toast('اكتب الاسم');const {error}=await client().from('platform_content').insert(row);if(error)return toast(error.message);toast('تم النشر');await openDeveloper();tab('publish')}
 async function removeContent(id){if(!confirm('حذف هذا المنشور؟'))return;const {error}=await client().from('platform_content').delete().eq('id',id);if(error)return toast(error.message);await openDeveloper();tab('publish')}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode)return switchMode(b.dataset.mode);if(b.dataset.tab)return tab(b.dataset.tab);if(b.dataset.action==='preview')return switchMode('user');if(b.dataset.action==='refresh')return openDeveloper();if(b.dataset.action==='create-code')return createCode();if(b.dataset.action==='publish')return publish();if(b.dataset.user)return setStatus(b.dataset.user,b.dataset.status);if(b.dataset.remove)return removeContent(b.dataset.remove)});
 document.addEventListener('change',e=>{if(e.target.matches('[data-section]'))section(e.target.dataset.section,e.target.checked)});
 async function guardSection(id){try{const {data}=await client().from('platform_sections').select('enabled').eq('section_key',id).maybeSingle();if(data?.enabled===false){showMaintenance();return false}}catch{}return true}
 function showMaintenance(){let o=$('maintenanceOverlay');if(!o){o=document.createElement('div');o.id='maintenanceOverlay';o.className='maintenance-overlay';document.body.appendChild(o)}o.innerHTML='<div><i>🛠</i><h2>القسم تحت الصيانة</h2><p>نعمل على تطوير هذا القسم وسيعود قريبًا.</p><button type="button" data-action="close-maintenance">رجوع</button></div>';o.querySelector('button').onclick=()=>o.remove()}
 const oldOpen=window.openSection;if(oldOpen)window.openSection=async id=>{if(await guardSection(id))return oldOpen(id)};
 window.tajDev={switchMode,openDeveloper,refresh:openDeveloper,tab,createCode,section,publish,removeContent,setStatus};
 const boot=()=>setTimeout(init,450);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();try{client().auth.onAuthStateChange(()=>setTimeout(init,250))}catch{}
})();
