/* Taj Al Molook V26 — developer control center, pricing + store */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmtDate=v=>v?new Date(v).toLocaleString('ar-IQ'):'—';
  const normalizeR2Object=v=>{v=String(v||'').trim();if(!v)return '';if(/^https?:\/\//i.test(v)){try{v=decodeURIComponent(new URL(v).pathname.replace(/^\/+/,''));}catch(e){return ''}}return v.replace(/^\/+/, '')};
  const sectionNames={home:'الرئيسية',apps:'التطبيقات',games:'الألعاب',store:'المتجر','cloud-games':'الألعاب السحابية',links:'الروابط',settings:'الإعدادات'};
  const visibleSectionKeys=Object.keys(sectionNames);
  const restrictionKeys=['apps','games','store','cloud-games','links','settings'];
  const defaultSections=()=>visibleSectionKeys.map((k,i)=>({section_key:k,title:sectionNames[k],enabled:true,sort_order:i}));
  let sb=null,profile=null,mode='developer',currentTab='overview',schemaWarnings=[];
  let data={users:[],codes:[],sections:[],content:[],downloads:[],restrictions:[],adjustments:[],links:[],storeItems:[]};

  function client(){
    if(sb)return sb;
    if(!window.supabase||!window.TAJ_SUPABASE_URL||!window.TAJ_SUPABASE_KEY)throw Error('Supabase config missing');
    return sb=window.supabase.createClient(window.TAJ_SUPABASE_URL,window.TAJ_SUPABASE_KEY);
  }
  function isDev(p){return !!p&&String(p.role||'').toLowerCase()==='developer'&&Number(p.user_number)===1}
  async function me(){const {data:{user}}=await client().auth.getUser();if(!user)return null;const {data,error}=await client().from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;return data}
  function toast(msg,type='ok'){
    if(!document.body.classList.contains('dev-admin-mode')&&typeof window.showToast==='function'){window.showToast(msg);return}
    let box=$('tajV24Toast');if(!box){box=document.createElement('div');box.id='tajV24Toast';document.body.appendChild(box)}
    box.className='taj24-toast '+type;box.textContent=msg;box.classList.add('show');clearTimeout(box._t);box._t=setTimeout(()=>box.classList.remove('show'),2600);
  }
  function closeModal(){$('taj24Modal')?.remove()}
  function confirmSite(title,message,ok='متابعة',danger=false){return new Promise(resolve=>{closeModal();const x=document.createElement('div');x.id='taj24Modal';x.className='taj24-modal';x.innerHTML=`<div class="taj24-dialog"><div class="taj24-dialog-icon">${danger?'⚠️':'👑'}</div><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="taj24-dialog-actions"><button data-no>إلغاء</button><button data-yes class="${danger?'danger':''}">${esc(ok)}</button></div></div>`;document.body.appendChild(x);const done=v=>{x.remove();resolve(v)};x.querySelector('[data-no]').onclick=()=>done(false);x.querySelector('[data-yes]').onclick=()=>done(true);x.onclick=e=>{if(e.target===x)done(false)}})}
  function askNumber(title,label,value=0){return new Promise(resolve=>{closeModal();const x=document.createElement('div');x.id='taj24Modal';x.className='taj24-modal';x.innerHTML=`<div class="taj24-dialog"><h3>${esc(title)}</h3><label class="taj24-field"><span>${esc(label)}</span><input id="taj24AskNum" type="number" value="${Number(value)||0}"></label><div class="taj24-dialog-actions"><button data-no>إلغاء</button><button data-yes>حفظ</button></div></div>`;document.body.appendChild(x);const done=v=>{x.remove();resolve(v)};x.querySelector('[data-no]').onclick=()=>done(null);x.querySelector('[data-yes]').onclick=()=>done(Number(x.querySelector('#taj24AskNum').value));x.onclick=e=>{if(e.target===x)done(null)};setTimeout(()=>x.querySelector('input')?.focus(),30)})}
  async function safe(name,fn){try{const r=await fn(client().from(name));if(r.error){schemaWarnings.push(name+': '+r.error.message);return []}return r.data||[]}catch(e){schemaWarnings.push(name+': '+e.message);return []}}
  function mergeSections(rows){return defaultSections().map(d=>{const x=(rows||[]).find(v=>v.section_key===d.section_key);return x?{...d,...x}:d})}
  function contentSection(x){const raw=String(x.section_key||'').toLowerCase();if(raw==='paid-games')return 'games';if(raw==='emulators')return 'apps';if(raw==='apps'||raw==='games'||raw==='cloud-games')return raw;return String(x.content_type||'').toLowerCase()==='app'?'apps':'games'}
  async function loadData(){
    schemaWarnings=[];
    const [users,codes,sections,content,downloads,restrictions,adjustments,links,storeItems]=await Promise.all([
      safe('profiles',q=>q.select('*').order('user_number',{ascending:true}).limit(500)),
      safe('subscription_codes',q=>q.select('*').order('created_at',{ascending:false}).limit(500)),
      safe('platform_sections',q=>q.select('*').order('sort_order',{ascending:true})),
      safe('platform_content',q=>q.select('*').order('created_at',{ascending:false}).limit(500)),
      safe('content_downloads',q=>q.select('*').order('created_at',{ascending:false}).limit(1000)),
      safe('user_section_restrictions',q=>q.select('*').limit(2000)),
      safe('code_time_adjustments',q=>q.select('*').limit(1000)),
      safe('platform_links',q=>q.select('*').order('platform',{ascending:true})),
      safe('platform_store_items',q=>q.select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false}).limit(500))
    ]);
    data={users,codes,sections:mergeSections(sections),content,downloads,restrictions,adjustments,links,storeItems};
  }
  const statDownloads=()=>data.content.reduce((n,x)=>n+Number(x.download_count||0),0);
  const statNewCodes=()=>data.codes.filter(x=>!x.used_by).length;
  const statUsedCodes=()=>data.codes.filter(x=>!!x.used_by).length;
  const statApps=()=>data.content.filter(x=>contentSection(x)==='apps').length;
  const statGames=()=>data.content.filter(x=>contentSection(x)==='games').length;
  const statStore=()=>data.storeItems.filter(x=>x.enabled!==false).length;
  const statOpenSections=()=>data.sections.filter(x=>x.enabled!==false).length;

  function closeUserLayers(){document.querySelectorAll('.full-screen-view.active').forEach(x=>x.classList.remove('active'));$('sideDrawer')?.classList.remove('active');$('sidebarBackdrop')?.classList.remove('active')}
  function showReturnButton(){let b=$('devPreviewReturn');if(mode==='user'){if(!b){b=document.createElement('button');b.id='devPreviewReturn';b.className='dev-preview-return-v24';b.innerHTML='👑 العودة إلى المطور';b.onclick=()=>switchMode('developer');document.body.appendChild(b)}}else b?.remove()}
  function setModeClasses(){document.documentElement.classList.toggle('taj-developer-session',isDev(profile));document.body.classList.toggle('dev-admin-mode',mode==='developer');document.body.classList.toggle('dev-user-preview-mode',mode==='user');showReturnButton()}
  async function switchMode(next,openKey){if(!isDev(profile))return;mode=next==='user'?'user':'developer';localStorage.setItem('taj_dev_mode_v26',mode);if(mode==='developer'){closeUserLayers();setModeClasses();await openDeveloper()}else{$('developerCenter')?.remove();setModeClasses();if(openKey)setTimeout(()=>window.openSection?.(openKey),80)}}

  function shell(){
    let root=$('developerCenter');if(!root){root=document.createElement('section');root.id='developerCenter';document.body.appendChild(root)}
    root.className='developer-center-v24';
    root.innerHTML=`<div class="dev24-shell">
      <header class="dev24-head"><div><span class="dev24-kicker">TAJ AL MULUK • ADMIN V26</span><h1>👑 مركز تحكم المطور</h1><p>ID 1 • الألعاب والتطبيقات والمتجر والحسابات والأكواد والروابط</p></div><div class="dev24-head-actions"><button data-action="preview">👤 معاينة المستخدم</button><button data-action="refresh">↻ تحديث</button></div></header>
      <section class="dev24-stats dev26-stats">
        <article><span class="stat-icon">👥</span><b>${data.users.length}</b><span>الحسابات</span></article>
        <article><span class="stat-icon">📱</span><b>${statApps()}</b><span>التطبيقات</span></article>
        <article><span class="stat-icon">🎮</span><b>${statGames()}</b><span>الألعاب</span></article>
        <article><span class="stat-icon">🛒</span><b>${statStore()}</b><span>عروض المتجر</span></article>
        <article><span class="stat-icon">⬇</span><b>${statDownloads().toLocaleString('en-US')}</b><span>التنزيلات</span></article>
        <article><span class="stat-icon">🟢</span><b>${statNewCodes()}</b><span>أكواد متاحة</span></article>
        <article><span class="stat-icon">🔴</span><b>${statUsedCodes()}</b><span>أكواد مفعلة</span></article>
      </section>
      <nav class="dev24-tabs"><button data-tab="overview">⌂ الرئيسية</button><button data-tab="publish">🚀 رفع تطبيق/لعبة</button><button data-tab="content">🎮 المحتوى</button><button data-tab="store">🛒 المتجر</button><button data-tab="codes">🔑 الأكواد</button><button data-tab="users">👥 الحسابات</button><button data-tab="sections">⚙ الأقسام</button><button data-tab="links">🔗 الروابط</button></nav>
      <main id="devPanelV24"></main></div>`;
    root.onclick=handleClick;root.onchange=handleChange;renderTab(currentTab);
  }
  async function openDeveloper(){if(mode!=='developer')return;setModeClasses();let root=$('developerCenter');if(!root){root=document.createElement('section');root.id='developerCenter';root.className='developer-center-v24';document.body.appendChild(root)}root.innerHTML='<div class="dev24-loading">👑 جاري تحميل لوحة المطور…</div>';await loadData();if(mode==='developer')shell()}
  function renderTab(name){currentTab=name;const p=$('devPanelV24');if(!p)return;document.querySelectorAll('.dev24-tabs [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='overview')return renderOverview(p);if(name==='publish')return renderPublish(p);if(name==='content')return renderContent(p);if(name==='store')return renderStore(p);if(name==='codes')return renderCodes(p);if(name==='users')return renderUsers(p);if(name==='sections')return renderSections(p);if(name==='links')return renderLinks(p)}
  function renderOverview(p){const locked=data.content.filter(x=>x.locked).length,blocked=data.sections.filter(x=>x.enabled===false).length;const needsV26=schemaWarnings.some(x=>x.startsWith('platform_store_items:')||/old_price/i.test(x));const warn=needsV26?`<div class="dev24-warning"><b>⚠️ يلزم تشغيل SQL V26 مرة واحدة</b><small>شغّل supabase-v26-store-pricing.sql حتى تعمل أسعار التطبيقات ومتجر الأرصدة والأكواد.</small></div>`:'';p.innerHTML=`${warn}<section class="dev24-card dev24-hero"><h2>لوحة المطور V26</h2><p>عدادات مرتبة، رفع الألعاب والتطبيقات بسعر سابق وتنزيل مجاني، ومتجر مستقل للأرصدة والأكواد.</p><div class="dev24-mini"><span><b>${locked}</b> عناصر مقفلة</span><span><b>${blocked}</b> أقسام مقفلة</span><span><b>${statOpenSections()}</b> أقسام مفتوحة</span><span><b>${data.downloads.length}</b> سجل تنزيل</span></div></section>`}

  function renderPublish(p){p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>🚀 رفع لعبة أو تطبيق</h2><p>حدّد السعر السابق فقط؛ يظهر للمستخدم باللون الأحمر وعليه خط، بينما التنزيل الحالي يظهر «مجاني».</p></div></div><div class="dev24-publish-grid">
    <label class="taj24-field"><span>الاسم</span><input id="pubName" autocomplete="off" placeholder="مثال: LIMBO"></label>
    <label class="taj24-field"><span>الإصدار</span><input id="pubVersion" autocomplete="off" placeholder="مثال: 1.0.8"></label>
    <label class="taj24-field"><span>القسم</span><select id="pubSection"><option value="games">الألعاب</option><option value="apps">التطبيقات</option></select></label>
    <label class="taj24-field"><span>السعر السابق</span><input id="pubOldPrice" autocomplete="off" placeholder="مثال: 12,000 د.ع"></label>
    <label class="taj24-field wide"><span>اسم ملف APK داخل R2</span><input id="pubR2" autocomplete="off" placeholder="LIMBO.apk أو apps/LIMBO.apk"></label>
    <label class="taj24-field wide"><span>رابط الفتح المباشر (اختياري)</span><input id="pubOpenUrl" type="url" autocomplete="off" placeholder="https://example.com/app"></label>
    <label class="taj24-field"><span>الحجم</span><input id="pubSize" autocomplete="off" placeholder="102.01 MB"></label>
    <label class="taj24-field dev24-file"><span>صورة الغلاف</span><input id="pubImageFile" type="file" accept="image/jpeg,image/png,image/webp"></label>
    <div class="dev24-preview"><img id="pubImagePreview" alt=""><span id="pubImageEmpty">لا توجد صورة مختارة</span></div>
    <div class="dev26-price-preview wide"><span class="taj-old-price" id="pubPricePreview">السعر السابق</span><strong class="taj-free-price">مجاني</strong></div>
    <label class="taj24-field wide"><span>النبذة</span><textarea id="pubDesc" placeholder="وصف مختصر وواضح"></textarea></label>
    <button class="dev24-primary wide" data-action="publish">🚀 نشر الآن</button>
    </div></section>`;setTimeout(bindPublishForm,0)}
  function bindPublishForm(){const f=$('pubImageFile'),im=$('pubImagePreview'),empty=$('pubImageEmpty'),price=$('pubOldPrice'),preview=$('pubPricePreview');if(f)f.onchange=()=>{const z=f.files?.[0];if(!z){if(im)im.removeAttribute('src');if(empty)empty.hidden=false;return}if(im){im.src=URL.createObjectURL(z);im.style.display='block'}if(empty)empty.hidden=true};if(price&&preview){const sync=()=>preview.textContent=price.value.trim()||'السعر السابق';price.oninput=sync;sync()}}
  function contentCard(x){const dl=Number(x.download_count||0),sec=contentSection(x);return `<article class="dev24-content-row ${x.locked?'is-locked':''}"><img src="${esc(x.image_url||'')}" alt="" loading="lazy" decoding="async" onerror="this.style.visibility='hidden'"><div class="dev24-content-info"><h3>${esc(x.name||'بدون اسم')}</h3><p>${esc(sectionNames[sec]||sec)} • ${esc(x.version||'—')} • ${esc(x.size_text||'—')}</p><div class="dev26-inline-price">${x.old_price?`<del>${esc(x.old_price)}</del>`:''}<strong>مجاني</strong></div><div class="dev24-badges"><span>⬇ ${dl.toLocaleString('en-US')} تنزيل</span>${x.open_url?'<span class="on">↗ فتح مباشر</span>':''}<span class="${x.published===false?'off':'on'}">${x.published===false?'مخفي':'منشور'}</span><span class="${x.locked?'off':'on'}">${x.locked?'مقفول':'مفتوح'}</span></div></div><div class="dev24-actions"><button data-content-edit="${esc(x.id)}">تعديل</button><button data-content-lock="${esc(x.id)}" data-next="${x.locked?'false':'true'}">${x.locked?'فتح':'قفل'}</button><button data-toggle-pub="${esc(x.id)}" data-next="${x.published===false?'true':'false'}">${x.published===false?'إظهار':'إخفاء'}</button><button class="danger" data-delete="${esc(x.id)}">حذف</button></div></article>`}
  function renderContent(p){const keys=['games','apps','cloud-games'];const blocks=keys.map(k=>{const list=data.content.filter(x=>contentSection(x)===k);if(!list.length)return '';return `<section class="dev25-section-block"><div class="dev25-section-head"><h3>${esc(sectionNames[k]||k)}</h3><span>${list.length} عنصر</span></div><div class="dev24-content-list">${list.map(contentCard).join('')}</div></section>`}).join('');p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>🎮 الألعاب والتطبيقات</h2><p>الألعاب المدفوعة القديمة تُعرض الآن داخل الألعاب، ومحتوى المحاكي القديم يُعرض داخل التطبيقات.</p></div><button data-action="go-publish">＋ إضافة جديد</button></div>${blocks||'<p class="dev24-empty">لا توجد منشورات حاليًا.</p>'}</section>`}

  function storeCard(x){return `<article class="dev26-store-admin-row"><div class="dev26-store-admin-main">${x.image_url?`<img src="${esc(x.image_url)}" loading="lazy" decoding="async" alt="">`:`<span class="dev26-store-icon">${x.item_type==='code'?'🔑':'💰'}</span>`}<div><h3>${esc(x.title||'عرض')}</h3><p>${x.item_type==='code'?'كود':'رصيد'} • ${esc(x.value_text||'—')}</p><strong>${esc(x.price_text||'—')}</strong></div></div><div class="dev24-actions"><button data-store-edit="${esc(x.id)}">تعديل</button><button data-store-toggle="${esc(x.id)}" data-next="${x.enabled===false?'true':'false'}">${x.enabled===false?'إظهار':'إخفاء'}</button><button class="danger" data-store-delete="${esc(x.id)}">حذف</button></div></article>`}
  function renderStore(p){const sqlWarn=schemaWarnings.some(x=>x.startsWith('platform_store_items:'))?'<div class="dev24-warning"><b>شغّل SQL V26 أولًا</b><small>بدون الجدول الجديد لن يتم حفظ عروض المتجر.</small></div>':'';p.innerHTML=`${sqlWarn}<section class="dev24-card"><div class="dev24-card-title"><div><h2>🛒 نشر في المتجر</h2><p>اختَر «رصيد» أو «كود» ثم انشر العرض ليظهر مباشرة للمستخدمين.</p></div></div><div class="dev24-publish-grid"><label class="taj24-field"><span>نوع العرض</span><select id="storeType"><option value="balance">رصيد</option><option value="code">كود</option></select></label><label class="taj24-field"><span>اسم العرض</span><input id="storeTitle" placeholder="مثال: رصيد 10,000 نقطة"></label><label class="taj24-field"><span>القيمة / المدة</span><input id="storeValue" placeholder="مثال: 10,000 نقطة أو 30 يوم"></label><label class="taj24-field"><span>السعر</span><input id="storePrice" placeholder="مثال: 5,000 د.ع"></label><label class="taj24-field wide"><span>صورة العرض (اختياري)</span><input id="storeImage" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="taj24-field wide"><span>الوصف</span><textarea id="storeDesc" placeholder="تفاصيل العرض"></textarea></label><button class="dev24-primary wide" data-action="publish-store">＋ نشر العرض</button></div></section><section class="dev24-card"><h2>العروض المنشورة</h2><div class="dev26-store-admin-list">${data.storeItems.map(storeCard).join('')||'<p class="dev24-empty">لا توجد عروض بعد.</p>'}</div></section>`}

  function codeUserName(id){const u=data.users.find(x=>String(x.id)===String(id));return u?(u.display_name||u.username||('ID '+u.user_number)):''}
  function renderCodes(p){p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>🔑 إنشاء كود</h2><p>الكود الجديد أخضر «غير مفعل»، وبعد استخدامه يصبح أحمر «مفعل» ولا يستخدم مرة ثانية.</p></div></div><div class="dev24-code-create"><label class="taj24-field"><span>نوع الكود</span><select id="dcType"><option value="trial">تجريبي</option><option value="basic">أساسي</option></select></label><label class="taj24-field"><span>المدة بالدقائق</span><input id="dcMinutes" type="number" min="1" value="60"></label><button class="dev24-primary" data-action="create-code">＋ إنشاء الكود</button></div></section><section class="dev24-card"><h2>الأكواد</h2><div class="dev24-code-list">${data.codes.map(x=>`<div class="dev24-code-row ${x.used_by?'used':'new'}"><div><b>${esc(x.code)}</b><small>${esc(x.code_type||'')} • ${Number(x.duration_minutes||0).toLocaleString('en-US')} دقيقة${x.used_by?' • '+esc(codeUserName(x.used_by)):''}</small></div><span>${x.used_by?'🔴 مفعل':'🟢 غير مفعل'}</span></div>`).join('')||'<p class="dev24-empty">لا توجد أكواد حاليًا.</p>'}</div></section>`}
  function userDownloads(id){return data.downloads.filter(x=>String(x.user_id)===String(id))}
  function userCode(id){return data.codes.find(x=>String(x.used_by)===String(id))||null}
  function renderUsers(p){p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>👥 الحسابات</h2><p>افتح الحساب لمشاهدة التنزيلات والكود والنقاط والصلاحيات والتحكم بها.</p></div></div><div class="dev24-users">${data.users.map(u=>`<article class="dev24-user-row"><div><b>${esc(u.display_name||u.username||'حساب')}</b><small>ID ${esc(u.user_number??u.public_id??'—')} • ${Number(u.points||0).toLocaleString('en-US')} نقطة • ${esc(u.account_status||'active')}</small></div><div class="dev24-user-count">⬇ ${userDownloads(u.id).length}</div><button data-user-open="${esc(u.id)}">فتح الحساب</button></article>`).join('')||'<p class="dev24-empty">لا توجد حسابات.</p>'}</div></section>`}
  function renderSections(p){p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>⚙ إدارة الأقسام</h2><p>الأقسام الحالية فقط؛ تستطيع قفل القسم للجميع أو فتحه في معاينة المستخدم.</p></div></div><div class="dev24-sections">${data.sections.map(s=>`<article class="dev24-section-row"><div><b>${esc(sectionNames[s.section_key]||s.title||s.section_key)}</b><small>${esc(s.section_key)}</small></div><label class="dev24-switch"><input type="checkbox" data-section="${esc(s.section_key)}" ${s.enabled!==false?'checked':''}><span></span></label><button data-preview-section="${esc(s.section_key)}">فتح القسم</button></article>`).join('')}</div></section>`}

  const socialDefs={telegram:{title:'Telegram',icon:'fa-telegram',placeholder:'https://t.me/your_account'},tiktok:{title:'TikTok',icon:'fa-tiktok',placeholder:'https://www.tiktok.com/@your_account'},instagram:{title:'Instagram',icon:'fa-instagram',placeholder:'https://www.instagram.com/your_account'}};
  function linkRow(platform){return data.links.find(x=>x.platform===platform)||{}}
  function renderLinks(p){p.innerHTML=`<section class="dev24-card"><div class="dev24-card-title"><div><h2>🔗 الروابط الرسمية</h2><p>Telegram وTikTok وInstagram تظهر للمستخدمين في قسم الروابط.</p></div></div><div class="dev25-social-grid">${Object.entries(socialDefs).map(([key,d])=>{const x=linkRow(key);return `<article class="dev25-social-card"><div class="dev25-social-title"><i class="fa-brands ${d.icon}"></i><h3>${d.title}</h3></div><label class="taj24-field"><span>اسم الحساب</span><input id="linkLabel-${key}" value="${esc(x.label||'')}" placeholder="مثال: @ZLZ"></label><label class="taj24-field"><span>الرابط</span><input id="linkUrl-${key}" value="${esc(x.url||'')}" placeholder="${d.placeholder}"></label><label class="dev25-enabled"><span>إظهار للمستخدمين</span><input id="linkEnabled-${key}" type="checkbox" ${x.enabled===false?'':'checked'}></label><div class="dev25-social-actions"><button class="dev24-primary" data-save-link="${key}">حفظ</button><button class="danger" data-delete-link="${key}" ${x.url?'':'disabled'}>حذف</button></div></article>`}).join('')}</div></section>`}

  async function saveLink(platform){const def=socialDefs[platform];if(!def)return;const label=$('linkLabel-'+platform)?.value.trim()||'',url=$('linkUrl-'+platform)?.value.trim()||'',enabled=!!$('linkEnabled-'+platform)?.checked;if(!url)return toast('اكتب رابط '+def.title,'error');if(!/^https:\/\//i.test(url))return toast('الرابط يجب أن يبدأ بـ https://','error');const {error}=await client().from('platform_links').upsert({platform,label,url,enabled,updated_at:new Date().toISOString()},{onConflict:'platform'});if(error)return toast('خطأ: '+error.message,'error');toast('✅ تم حفظ رابط '+def.title);await loadData();renderTab('links');window.tajLinks?.reload?.()}
  async function deleteLink(platform){const def=socialDefs[platform];if(!def)return;if(!await confirmSite('حذف الرابط','سيتم حذف رابط '+def.title+' من قسم الروابط.','حذف',true))return;const {error}=await client().from('platform_links').delete().eq('platform',platform);if(error)return toast('خطأ: '+error.message,'error');toast('تم حذف الرابط');await loadData();renderTab('links');window.tajLinks?.reload?.()}

  async function handleClick(e){
    const tb=e.target.closest('[data-tab]');if(tb)return renderTab(tb.dataset.tab);
    const a=e.target.closest('[data-action]');if(a){const k=a.dataset.action;if(k==='preview')return switchMode('user');if(k==='refresh')return refresh();if(k==='create-code')return createCode();if(k==='publish')return publishContent();if(k==='publish-store')return publishStore();if(k==='go-publish')return renderTab('publish')}
    const del=e.target.closest('[data-delete]');if(del)return removeContent(del.dataset.delete);
    const tog=e.target.closest('[data-toggle-pub]');if(tog)return toggleContent(tog.dataset.togglePub,tog.dataset.next==='true');
    const lock=e.target.closest('[data-content-lock]');if(lock)return setContentLock(lock.dataset.contentLock,lock.dataset.next==='true');
    const edit=e.target.closest('[data-content-edit]');if(edit)return editContent(edit.dataset.contentEdit);
    const se=e.target.closest('[data-store-edit]');if(se)return editStore(se.dataset.storeEdit);
    const st=e.target.closest('[data-store-toggle]');if(st)return toggleStore(st.dataset.storeToggle,st.dataset.next==='true');
    const sd=e.target.closest('[data-store-delete]');if(sd)return removeStore(sd.dataset.storeDelete);
    const saveLinkBtn=e.target.closest('[data-save-link]');if(saveLinkBtn)return saveLink(saveLinkBtn.dataset.saveLink);
    const deleteLinkBtn=e.target.closest('[data-delete-link]');if(deleteLinkBtn)return deleteLink(deleteLinkBtn.dataset.deleteLink);
    const u=e.target.closest('[data-user-open]');if(u)return openUser(u.dataset.userOpen);
    const prev=e.target.closest('[data-preview-section]');if(prev)return switchMode('user',prev.dataset.previewSection);
  }
  async function handleChange(e){const c=e.target.closest('[data-section]');if(c)return setSection(c.dataset.section,c.checked)}
  async function refresh(){await loadData();shell();renderTab(currentTab);toast('تم تحديث البيانات')}
  async function createCode(){const type=$('dcType')?.value||'trial',mins=Math.max(1,Number($('dcMinutes')?.value||60));let r=await client().rpc('admin_generate_code',{p_type:type,p_duration_minutes:mins});if(r.error)r=await client().rpc('admin_create_code',{p_type:type,p_duration_minutes:mins});if(r.error)r=await client().rpc('admin_create_code_v24',{p_type:type,p_duration_minutes:mins});if(r.error)return toast('تعذر إنشاء الكود: '+r.error.message,'error');toast('✅ تم إنشاء الكود: '+String(r.data||''));await loadData();renderTab('codes')}
  async function setSection(key,enabled){const {error}=await client().from('platform_sections').upsert({section_key:key,title:sectionNames[key]||key,enabled,updated_at:new Date().toISOString()},{onConflict:'section_key'});if(error){toast('خطأ: '+error.message,'error');return}toast(enabled?'✅ تم فتح القسم':'🔒 تم قفل القسم');await loadData();renderTab('sections')}
  async function uploadCover(file){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`covers/${Date.now()}-${Math.random().toString(36).slice(2,9)}.${ext}`;const up=await client().storage.from('content-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(up.error)throw up.error;return client().storage.from('content-images').getPublicUrl(path).data.publicUrl}

  async function publishContent(){
    const name=$('pubName')?.value.trim(),file=$('pubImageFile')?.files?.[0],r2=normalizeR2Object($('pubR2')?.value);if(!name)return toast('اكتب اسم اللعبة أو التطبيق','error');if(!r2)return toast('اكتب اسم ملف APK الموجود في R2','error');if(!file)return toast('اختر صورة الغلاف','error');
    const btn=document.querySelector('[data-action="publish"]');if(btn){btn.disabled=true;btn.textContent='جاري الحفظ…'}
    try{const image=await uploadCover(file);const sectionKey=$('pubSection')?.value==='apps'?'apps':'games';const row={name,version:$('pubVersion')?.value.trim(),content_type:sectionKey==='apps'?'app':'game',section_key:sectionKey,r2_object:r2,download_url:r2,open_url:$('pubOpenUrl')?.value.trim()||null,size_text:$('pubSize')?.value.trim(),image_url:image,description:$('pubDesc')?.value.trim(),old_price:$('pubOldPrice')?.value.trim()||null,published:true,locked:false};let r=await client().from('platform_content').insert(row);if(r.error&&/(old_price|open_url)/i.test(r.error.message||'')){const fallback={...row};if(/old_price/i.test(r.error.message||''))delete fallback.old_price;if(/open_url/i.test(r.error.message||''))delete fallback.open_url;r=await client().from('platform_content').insert(fallback);if(!r.error)toast('تم النشر، لكن شغّل SQL V27 لتفعيل جميع الحقول الجديدة','error')}if(r.error)throw r.error;toast('✅ تم نشر المحتوى');await loadData();renderTab('content');window.tajStore?.reload?.()}catch(e){toast('خطأ: '+e.message,'error')}finally{if(btn){btn.disabled=false;btn.textContent='🚀 نشر الآن'}}
  }
  async function toggleContent(id,published){const {error}=await client().from('platform_content').update({published}).eq('id',id);if(error)return toast(error.message,'error');toast(published?'تم إظهار المحتوى':'تم إخفاء المحتوى');await loadData();renderTab('content');window.tajStore?.reload?.()}
  async function setContentLock(id,locked){let r=await client().rpc('admin_set_content_lock_v24',{p_content:String(id),p_locked:locked});if(r.error)r=await client().from('platform_content').update({locked}).eq('id',id);if(r.error)return toast(r.error.message,'error');toast(locked?'🔒 تم قفل العنصر':'✅ تم فتح العنصر');await loadData();renderTab('content');window.tajStore?.reload?.()}
  async function removeContent(id){if(!await confirmSite('حذف المنشور','سيتم حذف هذا المنشور من المنصة. هل تريد المتابعة؟','حذف',true))return;const {error}=await client().from('platform_content').delete().eq('id',id);if(error)return toast('خطأ: '+error.message,'error');toast('تم حذف المنشور');await loadData();renderTab('content');window.tajStore?.reload?.()}
  async function editContent(id){
    const x=data.content.find(v=>String(v.id)===String(id));if(!x)return;closeModal();const sec=contentSection(x);const m=document.createElement('div');m.id='taj24Modal';m.className='taj24-modal';m.innerHTML=`<div class="taj24-dialog taj24-edit"><h3>✏️ تعديل ${esc(x.name)}</h3><div class="dev24-publish-grid"><label class="taj24-field"><span>الاسم</span><input id="eName" value="${esc(x.name||'')}"></label><label class="taj24-field"><span>الإصدار</span><input id="eVersion" value="${esc(x.version||'')}"></label><label class="taj24-field"><span>القسم</span><select id="eSection"><option value="games" ${sec==='games'?'selected':''}>الألعاب</option><option value="apps" ${sec==='apps'?'selected':''}>التطبيقات</option></select></label><label class="taj24-field"><span>السعر السابق</span><input id="eOldPrice" value="${esc(x.old_price||'')}"></label><label class="taj24-field"><span>الحجم</span><input id="eSize" value="${esc(x.size_text||'')}"></label><label class="taj24-field wide"><span>ملف R2</span><input id="eR2" value="${esc(x.r2_object||x.download_url||'')}"></label><label class="taj24-field wide"><span>رابط الفتح المباشر (اختياري)</span><input id="eOpenUrl" type="url" value="${esc(x.open_url||'')}"></label><label class="taj24-field wide"><span>صورة جديدة (اختياري)</span><input id="eImage" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="taj24-field wide"><span>النبذة</span><textarea id="eDesc">${esc(x.description||'')}</textarea></label></div><div class="taj24-dialog-actions"><button data-no>إلغاء</button><button data-yes>حفظ التعديل</button></div></div>`;document.body.appendChild(m);m.querySelector('[data-no]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('[data-yes]').onclick=async()=>{const btn=m.querySelector('[data-yes]');btn.disabled=true;try{const file=$('eImage')?.files?.[0];let image=x.image_url;if(file)image=await uploadCover(file);const editSection=$('eSection').value;const row={name:$('eName').value.trim(),version:$('eVersion').value.trim(),section_key:editSection,content_type:editSection==='apps'?'app':'game',old_price:$('eOldPrice').value.trim()||null,size_text:$('eSize').value.trim(),r2_object:normalizeR2Object($('eR2').value),download_url:normalizeR2Object($('eR2').value),open_url:$('eOpenUrl')?.value.trim()||null,description:$('eDesc').value.trim(),image_url:image};let r=await client().from('platform_content').update(row).eq('id',id);if(r.error&&/(old_price|open_url)/i.test(r.error.message||'')){const fallback={...row};if(/old_price/i.test(r.error.message||''))delete fallback.old_price;if(/open_url/i.test(r.error.message||''))delete fallback.open_url;r=await client().from('platform_content').update(fallback).eq('id',id)}if(r.error)throw r.error;m.remove();toast('✅ تم حفظ التعديل');await loadData();renderTab('content');window.tajStore?.reload?.()}catch(e){toast(e.message,'error');btn.disabled=false}};
  }

  async function publishStore(){try{const title=$('storeTitle')?.value.trim(),type=$('storeType')?.value==='code'?'code':'balance',value=$('storeValue')?.value.trim(),price=$('storePrice')?.value.trim();if(!title)return toast('اكتب اسم العرض','error');if(!value)return toast('اكتب قيمة الرصيد أو مدة/نوع الكود','error');if(!price)return toast('اكتب السعر','error');const file=$('storeImage')?.files?.[0];const image=file?await uploadCover(file):null;const row={item_type:type,title,value_text:value,price_text:price,image_url:image,description:$('storeDesc')?.value.trim(),enabled:true,sort_order:0,updated_at:new Date().toISOString()};const {error}=await client().from('platform_store_items').insert(row);if(error)throw error;toast('✅ تم نشر العرض في المتجر');await loadData();renderTab('store');window.tajMarket?.reload?.()}catch(e){toast('خطأ: '+e.message+(String(e.message).includes('platform_store_items')?' — شغّل SQL V26 أولًا':''),'error')}}
  async function toggleStore(id,enabled){const {error}=await client().from('platform_store_items').update({enabled,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,'error');toast(enabled?'تم إظهار العرض':'تم إخفاء العرض');await loadData();renderTab('store');window.tajMarket?.reload?.()}
  async function removeStore(id){if(!await confirmSite('حذف العرض','سيتم حذف العرض من المتجر.','حذف',true))return;const {error}=await client().from('platform_store_items').delete().eq('id',id);if(error)return toast(error.message,'error');toast('تم حذف العرض');await loadData();renderTab('store');window.tajMarket?.reload?.()}
  async function editStore(id){const x=data.storeItems.find(v=>String(v.id)===String(id));if(!x)return;closeModal();const m=document.createElement('div');m.id='taj24Modal';m.className='taj24-modal';m.innerHTML=`<div class="taj24-dialog taj24-edit"><h3>✏️ تعديل العرض</h3><div class="dev24-publish-grid"><label class="taj24-field"><span>النوع</span><select id="seType"><option value="balance" ${x.item_type==='balance'?'selected':''}>رصيد</option><option value="code" ${x.item_type==='code'?'selected':''}>كود</option></select></label><label class="taj24-field"><span>الاسم</span><input id="seTitle" value="${esc(x.title||'')}"></label><label class="taj24-field"><span>القيمة / المدة</span><input id="seValue" value="${esc(x.value_text||'')}"></label><label class="taj24-field"><span>السعر</span><input id="sePrice" value="${esc(x.price_text||'')}"></label><label class="taj24-field wide"><span>صورة جديدة (اختياري)</span><input id="seImage" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="taj24-field wide"><span>الوصف</span><textarea id="seDesc">${esc(x.description||'')}</textarea></label></div><div class="taj24-dialog-actions"><button data-no>إلغاء</button><button data-yes>حفظ</button></div></div>`;document.body.appendChild(m);m.querySelector('[data-no]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('[data-yes]').onclick=async()=>{const b=m.querySelector('[data-yes]');b.disabled=true;try{const file=$('seImage')?.files?.[0];let image=x.image_url;if(file)image=await uploadCover(file);const row={item_type:$('seType').value,title:$('seTitle').value.trim(),value_text:$('seValue').value.trim(),price_text:$('sePrice').value.trim(),image_url:image,description:$('seDesc').value.trim(),updated_at:new Date().toISOString()};const {error}=await client().from('platform_store_items').update(row).eq('id',id);if(error)throw error;m.remove();toast('تم حفظ العرض');await loadData();renderTab('store');window.tajMarket?.reload?.()}catch(e){toast(e.message,'error');b.disabled=false}}}

  async function openUser(id){const u=data.users.find(x=>String(x.id)===String(id));if(!u)return;const dls=userDownloads(id),code=userCode(id),blocked=data.restrictions.filter(x=>String(x.user_id)===String(id)&&x.blocked!==false),adj=code?data.adjustments.find(x=>String(x.user_id)===String(id)&&String(x.code)===String(code.code)):null;closeModal();const m=document.createElement('div');m.id='taj24Modal';m.className='taj24-modal';m.innerHTML=`<div class="taj24-dialog taj24-user-detail"><button class="taj24-x" data-close>×</button><h3>👤 ${esc(u.display_name||u.username||'حساب')}</h3><div class="dev24-user-summary"><span><b>ID</b>${esc(u.user_number??u.public_id??'—')}</span><span><b>النقاط</b>${Number(u.points||0).toLocaleString('en-US')}</span><span><b>الحالة</b>${esc(u.account_status||'active')}</span><span><b>التنزيلات</b>${dls.length}</span></div><section><h4>الكود</h4>${code?`<div class="dev24-code-row used"><div><b>${esc(code.code)}</b><small>${esc(code.code_type||'')} • ${Number(code.duration_minutes||0)} دقيقة${adj?' • تعديل الوقت '+Number(adj.adjust_minutes||0)+' دقيقة':''}</small></div><span>🔴 مفعل</span></div>`:'<p class="dev24-empty">لا يوجد كود مستخدم.</p>'}</section><section><h4>إدارة الحساب</h4><div class="dev24-control-grid"><button data-uaction="points">تعديل النقاط</button><button data-uaction="time" ${code?'':'disabled'}>تقليص/زيادة وقت الكود</button><button data-uaction="freeze">تجميد مؤقت</button><button data-uaction="kick">طرد الجلسة</button><button data-uaction="restricted">تقييد الحساب</button><button data-uaction="banned" class="danger">حظر الحساب</button><button data-uaction="active">فتح الحساب</button></div></section><section><h4>تقييد أقسام لهذا الحساب</h4><div class="dev24-user-sections">${restrictionKeys.map(k=>{const isBlocked=blocked.some(r=>r.section_key===k);return `<label><span>${esc(sectionNames[k])}</span><input type="checkbox" data-user-section="${esc(k)}" ${isBlocked?'checked':''}></label>`}).join('')}</div></section><section><h4>آخر التنزيلات</h4><div class="dev24-download-history">${dls.slice(0,30).map(d=>`<div><b>${esc(d.item_name||('محتوى '+d.content_id))}</b><small>${fmtDate(d.created_at)}</small></div>`).join('')||'<p class="dev24-empty">لا توجد تنزيلات مسجلة.</p>'}</div></section></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelectorAll('[data-uaction]').forEach(b=>b.onclick=()=>userAction(u,code,b.dataset.uaction,m));m.querySelectorAll('[data-user-section]').forEach(ch=>ch.onchange=()=>setUserSection(u.id,ch.dataset.userSection,ch.checked))}
  async function rpc(name,args){const r=await client().rpc(name,args);if(r.error)throw r.error;return r.data}
  async function userAction(u,code,action,modal){try{if(action==='points'){const n=await askNumber('تعديل النقاط','موجب للإضافة، سالب للخصم',0);if(n===null||!Number.isFinite(n)||n===0)return;await rpc('admin_adjust_points_v24',{p_user:u.id,p_amount:Math.trunc(n)});toast('تم تعديل النقاط')}else if(action==='time'){if(!code)return;const n=await askNumber('تعديل وقت الكود','اكتب رقمًا سالبًا للتقليص أو موجبًا للزيادة',-60);if(n===null||!Number.isFinite(n)||n===0)return;await rpc('admin_adjust_code_time_v24',{p_user:u.id,p_code:code.code,p_minutes:Math.trunc(n)});toast('تم تعديل وقت الكود')}else if(action==='freeze'){const n=await askNumber('تجميد الحساب','مدة التجميد بالدقائق، 0 لإلغاء التجميد',60);if(n===null)return;await rpc('admin_freeze_user_v24',{p_user:u.id,p_minutes:Math.max(0,Math.trunc(n))});toast(n>0?'تم تجميد الحساب':'تم إلغاء التجميد')}else if(action==='kick'){if(!await confirmSite('طرد المستخدم','سيتم إنهاء جلسته عند الفحص التالي.','طرد',true))return;await rpc('admin_kick_user_v24',{p_user:u.id});toast('تم إرسال أمر الطرد')}else if(['active','restricted','banned'].includes(action)){let r=await client().rpc('admin_set_account_status',{p_user:u.id,p_status:action});if(r.error)r=await client().rpc('admin_set_account_status_v24',{p_user:u.id,p_status:action});if(r.error)throw r.error;toast('تم تحديث حالة الحساب')}modal?.remove();await loadData();renderTab('users')}catch(e){toast('خطأ: '+e.message,'error')}}
  async function setUserSection(user,section,blocked){try{await rpc('admin_set_user_section_v24',{p_user:user,p_section:section,p_blocked:blocked});toast(blocked?'تم تقييد القسم لهذا الحساب':'تم فتح القسم لهذا الحساب');await loadData()}catch(e){toast('خطأ: '+e.message,'error')}}

  let guardCache={at:0,profile:null,sections:new Map(),blocked:new Set(),pending:null};
  async function refreshGuardCache(force=false){
    if(!force&&Date.now()-guardCache.at<60000)return guardCache;
    if(guardCache.pending)return guardCache.pending;
    guardCache.pending=(async()=>{try{
      const p=await me();
      const sectionReq=client().from('platform_sections').select('section_key,enabled');
      const restrictionReq=p?client().from('user_section_restrictions').select('section_key,blocked').eq('user_id',p.id):Promise.resolve({data:[],error:null});
      const [sRes,rRes]=await Promise.all([sectionReq,restrictionReq]);
      const sections=new Map((sRes.data||[]).map(x=>[x.section_key,x.enabled!==false]));
      const blocked=new Set((rRes.data||[]).filter(x=>x.blocked!==false).map(x=>x.section_key));
      guardCache={at:Date.now(),profile:p,sections,blocked,pending:null};
      return guardCache;
    }catch(e){console.warn('section guard cache',e);guardCache.at=Date.now();guardCache.pending=null;return guardCache}})();
    return guardCache.pending;
  }
  function notice(title,message){closeModal();const x=document.createElement('div');x.id='taj24Modal';x.className='taj24-modal';x.innerHTML=`<div class="taj24-dialog"><div class="taj24-dialog-icon">🔒</div><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="taj24-dialog-actions"><button data-yes>رجوع</button></div></div>`;document.body.appendChild(x);x.querySelector('[data-yes]').onclick=()=>x.remove();x.onclick=e=>{if(e.target===x)x.remove()}}
  async function guardSection(id){try{const g=await refreshGuardCache(false),p=g.profile;if(isDev(p))return true;if(p?.account_status==='banned'){notice('الحساب محظور','تم حظر هذا الحساب من الإدارة.');return false}if(p?.frozen_until&&new Date(p.frozen_until)>new Date()){notice('الحساب مجمّد','الحساب مجمّد حتى '+fmtDate(p.frozen_until));return false}if(!visibleSectionKeys.includes(id))return true;if(g.sections.has(id)&&g.sections.get(id)===false){notice('القسم مغلق','هذا القسم مغلق مؤقتًا من الإدارة.');return false}if(p&&g.blocked.has(id)){notice('القسم مقيّد','الإدارة قيّدت وصول هذا الحساب إلى هذا القسم.');return false}}catch(e){console.warn('section guard',e)}return true}
  function hookSections(){const original=window.openSection;if(typeof original==='function'&&!original.__taj26){const wrapped=async function(id){if(await guardSection(id))return original.apply(this,arguments)};wrapped.__taj26=true;window.openSection=wrapped}}
  async function init(){hookSections();refreshGuardCache(true).catch(()=>{});try{profile=await me();if(!isDev(profile)){document.documentElement.classList.remove('taj-developer-session');document.body.classList.remove('dev-admin-mode','dev-user-preview-mode');$('developerCenter')?.remove();$('devPreviewReturn')?.remove();return}mode=localStorage.getItem('taj_dev_mode_v26')==='user'?'user':'developer';setModeClasses();if(mode==='developer'){closeUserLayers();await openDeveloper()}}catch(e){console.warn('V26 developer init',e)}}
  window.tajDev={switchMode,openDeveloper,renderTab,refresh};
  document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250));if(document.readyState!=='loading')setTimeout(init,250);try{client().auth.onAuthStateChange(()=>{guardCache.at=0;setTimeout(init,180)})}catch(e){}
})();
