/* Taj Al Molook V12 — Developer Control Center */
(function(){
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 let sb=null, profile=null, mode='developer';
 function client(){return sb||(sb=window.supabase.createClient(window.TAJ_SUPABASE_URL,window.TAJ_SUPABASE_KEY))}
 async function me(){const {data:{user}}=await client().auth.getUser();if(!user)return null;const {data}=await client().from('profiles').select('*').eq('id',user.id).maybeSingle();return data}
 function toast(x){window.showToast?showToast(x):alert(x)}
 async function init(){try{profile=await me();const isDev=profile&&String(profile.role||'').toLowerCase()==='developer'&&Number(profile.user_number)===1;if(isDev){document.documentElement.classList.add('is-developer');addSwitch();if(localStorage.getItem('taj_dev_mode')!=='user')await openDeveloper();else enterUserPreview(false)}else{document.documentElement.classList.remove('is-developer');$('devModeSwitch')?.remove();$('developerCenter')?.remove()}}catch(e){console.warn('Developer init',e)}}
 function addSwitch(){if($('devModeSwitch'))return;const d=document.createElement('div');d.id='devModeSwitch';d.className='dev-mode-switch';d.innerHTML='<button id="devBtn" onclick="tajDev.switchMode(\'developer\')">👑 المطور <small>ID 1</small></button><button id="usrBtn" onclick="tajDev.switchMode(\'user\')">👤 معاينة المستخدم <small>ID 100</small></button>';document.body.appendChild(d)}
 function setSwitch(){document.body.classList.toggle('developer-preview',mode==='user');$('devBtn')?.classList.toggle('active',mode==='developer');$('usrBtn')?.classList.toggle('active',mode==='user')}
 async function switchMode(m){mode=m;localStorage.setItem('taj_dev_mode',m);setSwitch();if(m==='developer')openDeveloper();else enterUserPreview(true)}
 function enterUserPreview(notify=true){mode='user';setSwitch();$('developerCenter')?.remove();document.body.dataset.previewId='100';document.querySelectorAll('#guestBadge .member-text small').forEach(x=>x.textContent='ID: 100');if(notify)toast('👤 وضع معاينة المستخدم — ID 100');}
 async function openDeveloper(){mode='developer';setSwitch();document.body.dataset.previewId='';let root=$('developerCenter');if(!root){root=document.createElement('div');root.id='developerCenter';root.className='developer-center';document.body.appendChild(root)}root.innerHTML='<div class="dev-loading">👑 جاري تحميل لوحة المطور…</div>';await render(root)}
 async function render(root){const c=client();const [u,co,sec,apps]=await Promise.all([c.from('profiles').select('id,user_number,display_name,points,role').order('user_number').limit(200),c.from('subscription_codes').select('*').order('created_at',{ascending:false}).limit(100),c.from('platform_sections').select('*').order('sort_order'),c.from('platform_content').select('*').order('created_at',{ascending:false}).limit(100)]);
 const users=u.data||[],codes=co.data||[],sections=sec.data||defaultSections(),content=apps.data||[];
 root.innerHTML=`<div class="dev-shell"><header><div><b>👑 مركز تحكم تاج الملوك</b><small>Developer • ID 1</small></div><button onclick="tajDev.refresh()">↻ تحديث</button></header><div class="dev-stats"><span><b>${users.length}</b> حساب</span><span><b>${codes.length}</b> كود</span><span><b>${content.length}</b> منشور</span><span><b>${sections.filter(x=>x.enabled!==false).length}</b> قسم مفتوح</span></div><nav class="dev-tabs"><button onclick="tajDev.tab('overview')">⌂ الرئيسية</button><button onclick="tajDev.tab('codes')">🔑 الأكواد</button><button onclick="tajDev.tab('users')">👥 الحسابات</button><button onclick="tajDev.tab('sections')">⚙ الأقسام</button><button onclick="tajDev.tab('publish')">🚀 النشر</button></nav><main id="devPanel"></main></div>`;
 window.__devData={users,codes,sections,content};tab('overview')}
 function defaultSections(){return ['home','buy-code','activate-code','download-store','apps','games','cloud-games','links','emulators','paid-games','settings'].map((key,i)=>({section_key:key,title:key,enabled:true,sort_order:i}))}
 function tab(t){const p=$('devPanel'),d=window.__devData;if(!p||!d)return;if(t==='overview')p.innerHTML=`<section class="dev-hero"><h2>التحكم الكامل بالمنصة</h2><p>أنشئ الأكواد، تابع الحسابات، اقفل الأقسام للصيانة وانشر البرامج والألعاب من مكان واحد.</p></section>`;
 if(t==='codes')p.innerHTML=`<section class="dev-card"><h3>إنشاء كود</h3><div class="dev-form"><select id="dcType"><option value="trial">تجريبي</option><option value="basic">أساسي</option></select><input id="dcMinutes" type="number" value="60" min="1" placeholder="المدة بالدقائق"><button onclick="tajDev.createCode()">＋ إنشاء</button></div></section><section class="dev-card"><h3>الأكواد</h3>${d.codes.map(x=>`<div class="dev-row"><span><b>${esc(x.code)}</b><small>${esc(x.code_type)} • ${x.duration_minutes||0} دقيقة</small></span><em>${x.used_by?'مستخدم':'متاح'}</em></div>`).join('')||'<p>لا توجد أكواد</p>'}</section>`;
 if(t==='users')p.innerHTML=`<section class="dev-card"><h3>الحسابات</h3>${d.users.map(x=>`<div class="dev-row"><span><b>${esc(x.display_name||'حساب')}</b><small>ID ${esc(x.user_number)} • ${Number(x.points||0).toLocaleString()} نقطة</small></span><div><button onclick="tajV5?.setStatus?.('${x.id}','banned')">حظر</button><button onclick="tajV5?.setStatus?.('${x.id}','active')">فتح</button></div></div>`).join('')}</section>`;
 if(t==='sections')p.innerHTML=`<section class="dev-card"><h3>فتح وقفل الأقسام</h3><p class="dev-note">عند القفل يظهر للمستخدم: 🛠 تحت الصيانة</p>${d.sections.map(x=>`<label class="dev-row dev-toggle"><span><b>${esc(x.title||x.section_key)}</b><small>${esc(x.section_key)}</small></span><input type="checkbox" ${x.enabled!==false?'checked':''} onchange="tajDev.section('${esc(x.section_key)}',this.checked)"></label>`).join('')}</section>`;
 if(t==='publish')p.innerHTML=`<section class="dev-card"><h3>نشر برنامج أو لعبة</h3><div class="dev-form publish"><input id="pubName" placeholder="اسم البرنامج / اللعبة"><input id="pubVersion" placeholder="الإصدار مثال 1.0"><select id="pubType"><option value="app">تطبيق</option><option value="game">لعبة</option></select><input id="pubImage" placeholder="رابط الصورة"><input id="pubUrl" placeholder="رابط الملف / التنزيل"><textarea id="pubDesc" placeholder="الوصف"></textarea><button onclick="tajDev.publish()">🚀 نشر الآن</button></div><p class="dev-note">رفع الملفات مباشرة إلى R2 سيُربط في المرحلة القادمة؛ حاليًا يدعم رابط الملف.</p></section><section class="dev-card"><h3>المنشورات</h3>${d.content.map(x=>`<div class="dev-row"><span><b>${esc(x.name)}</b><small>${esc(x.content_type)} • ${esc(x.version||'')}</small></span><button onclick="tajDev.removeContent('${x.id}')">حذف</button></div>`).join('')||'<p>لا توجد منشورات</p>'}</section>`}
 async function createCode(){const type=$('dcType').value,min=+$('dcMinutes').value||60;let r=await client().rpc('admin_create_code',{p_type:type,p_duration_minutes:min});if(r.error){toast(r.error.message);return}toast('تم إنشاء الكود: '+r.data);openDeveloper()}
 async function section(key,enabled){const {error}=await client().from('platform_sections').upsert({section_key:key,title:key,enabled,updated_at:new Date().toISOString()},{onConflict:'section_key'});if(error)return toast(error.message);toast(enabled?'تم فتح القسم':'تم وضع القسم تحت الصيانة')}
 async function publish(){const row={name:$('pubName').value.trim(),version:$('pubVersion').value.trim(),content_type:$('pubType').value,image_url:$('pubImage').value.trim(),download_url:$('pubUrl').value.trim(),description:$('pubDesc').value.trim(),published:true};if(!row.name)return toast('اكتب الاسم');const {error}=await client().from('platform_content').insert(row);if(error)return toast(error.message);toast('تم النشر');openDeveloper()}
 async function removeContent(id){if(!confirm('حذف هذا المنشور؟'))return;const {error}=await client().from('platform_content').delete().eq('id',id);if(error)return toast(error.message);openDeveloper()}
 async function guardSection(id){try{const {data}=await client().from('platform_sections').select('enabled').eq('section_key',id).maybeSingle();if(data&&data.enabled===false){showMaintenance(id);return false}}catch(e){}return true}
 function showMaintenance(id){let o=$('maintenanceOverlay');if(!o){o=document.createElement('div');o.id='maintenanceOverlay';o.className='maintenance-overlay';document.body.appendChild(o)}o.innerHTML=`<div><i>🛠</i><h2>القسم تحت الصيانة</h2><p>نعمل على تطوير هذا القسم وسيعود قريبًا.</p><button onclick="this.closest('.maintenance-overlay').remove()">رجوع</button></div>`}
 const oldOpen=window.openSection; if(oldOpen)window.openSection=async function(id){if(await guardSection(id))return oldOpen(id)};
 window.tajDev={switchMode,openDeveloper,refresh:openDeveloper,tab,createCode,section,publish,removeContent};
 document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700)); if(document.readyState!=='loading')setTimeout(init,700); try{client().auth.onAuthStateChange(()=>setTimeout(init,350))}catch(e){}
})();
