(() => {
  const R2='https://pub-d5ab4b74ad9345d2b1095e21b03bda8c.r2.dev';
  const games=[{id:'limbo',name:'LIMBO',version:'Android',size:'102.01 MB',image:`${R2}/Limb.webp.jpg`,apk:`${R2}/LIMBO.apk`,description:'لعبة مغامرات وألغاز ذات أجواء غامضة. تحكم بالشخصية وتجاوز العقبات والألغاز للوصول إلى نهاية الرحلة.'}];
  let current=null, blobUrl=null;
  const $=id=>document.getElementById(id);
  function render(){ const g=$('r2GamesGrid'); if(!g)return; g.innerHTML=games.map(x=>`<button class="r2-game-card" data-id="${x.id}"><img src="${x.image}" alt="${x.name}" loading="lazy"><span class="r2-game-name">${x.name}</span><small>${x.version} • ${x.size}</small></button>`).join(''); g.onclick=e=>{const c=e.target.closest('.r2-game-card');if(c)open(c.dataset.id)}; }
  function open(id){current=games.find(x=>x.id===id);if(!current)return;$('r2DetailImage').src=current.image;$('r2DetailName').textContent=current.name;$('r2DetailVersion').textContent='الإصدار: '+current.version;$('r2DetailSize').textContent='الحجم: '+current.size;$('r2DetailDescription').textContent=current.description;$('r2ProgressWrap').hidden=true;$('r2InstallBtn').hidden=true;$('r2InstallNote').hidden=true;$('r2DownloadBtn').hidden=false;$('r2GameDetail').classList.add('active');$('r2GameDetail').setAttribute('aria-hidden','false');}
  function close(){$('r2GameDetail')?.classList.remove('active');$('r2GameDetail')?.setAttribute('aria-hidden','true');}
  function download(){if(!current)return;const btn=$('r2DownloadBtn');btn.disabled=true;$('r2ProgressWrap').hidden=false;const xhr=new XMLHttpRequest();xhr.open('GET',current.apk,true);xhr.responseType='blob';xhr.onprogress=e=>{if(e.lengthComputable){const p=Math.min(100,Math.round(e.loaded/e.total*100));$('r2ProgressText').textContent=p+'%';$('r2ProgressBar').style.width=p+'%';}};xhr.onload=()=>{btn.disabled=false;if(xhr.status>=200&&xhr.status<300){$('r2ProgressText').textContent='100%';$('r2ProgressBar').style.width='100%';if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(xhr.response);const a=document.createElement('a');a.href=blobUrl;a.download='LIMBO.apk';document.body.appendChild(a);a.click();a.remove();btn.hidden=true;$('r2InstallBtn').hidden=false;$('r2InstallNote').hidden=false;}else fail();};xhr.onerror=fail;xhr.send();function fail(){btn.disabled=false;if(window.showToast)showToast('تعذر تنزيل اللعبة. تحقق من الاتصال وإعدادات R2.');}}
  function install(){if(!current)return; /* Browser cannot silently install APK; hand off to Android/browser download handler. */ window.location.assign(current.apk);}
  document.addEventListener('DOMContentLoaded',()=>{render();$('r2DetailBack')?.addEventListener('click',close);$('r2DownloadBtn')?.addEventListener('click',download);$('r2InstallBtn')?.addEventListener('click',install);});
})();
