-- ZELZAL CHAT v2.4
-- نفّذ الملف كاملًا في Supabase SQL Editor.
-- مهم: إذا كانت عندك بيانات قديمة، خذ نسخة احتياطية أولًا.

create extension if not exists pgcrypto;

-- ===== المستخدمون =====
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 30),
  username text unique,
  role text not null default 'user' check (role in ('user','admin')),
  is_banned boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles add column if not exists is_banned boolean not null default false;

-- توليد username للحسابات القديمة التي لا تملكه
update public.profiles
set username = 'user_' || substr(replace(id::text,'-',''),1,8)
where username is null or btrim(username)='';

create unique index if not exists profiles_username_unique_idx on public.profiles(lower(username));

-- إنشاء الملف الشخصي تلقائيًا بعد التسجيل
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  base_username text;
begin
  base_username := lower(coalesce(new.raw_user_meta_data->>'username','user_' || substr(replace(new.id::text,'-',''),1,8)));
  insert into public.profiles(id,display_name,username)
  values(
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(new.email,'@',1), 'مستخدم'),
    base_username
  )
  on conflict (id) do nothing;
  return new;
exception when unique_violation then
  insert into public.profiles(id,display_name,username)
  values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'مستخدم'),base_username || '_' || substr(replace(new.id::text,'-',''),1,4))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- دالة آمنة لمعرفة هل المستخدم مدير
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;

-- ===== الرومات =====
create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 50),
  description text default '',
  welcome_text text default '',
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.rooms add column if not exists welcome_text text default '';

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  media_type text check (media_type is null or media_type in ('image','audio')),
  media_path text,
  media_duration integer,
  created_at timestamptz not null default now()
);
alter table public.messages add column if not exists media_type text;
alter table public.messages add column if not exists media_path text;
alter table public.messages add column if not exists media_duration integer;
create index if not exists messages_room_created_idx on public.messages(room_id,created_at);

-- ===== الرسائل الخاصة =====
create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  media_type text check (media_type is null or media_type in ('image','audio')),
  media_path text,
  media_duration integer,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);
alter table public.private_messages add column if not exists media_type text;
alter table public.private_messages add column if not exists media_path text;
alter table public.private_messages add column if not exists media_duration integer;
alter table public.private_messages add column if not exists delivered_at timestamptz;
create index if not exists private_messages_sender_idx on public.private_messages(sender_id,created_at desc);
create index if not exists private_messages_receiver_idx on public.private_messages(receiver_id,created_at desc);


-- ===== إيصالات قراءة رسائل الرومات =====
create table if not exists public.room_message_reads (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key(message_id,user_id)
);
alter table public.room_message_reads enable row level security;

DROP POLICY IF EXISTS "room_reads_select_authenticated" ON public.room_message_reads;
CREATE POLICY "room_reads_select_authenticated" ON public.room_message_reads FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "room_reads_insert_own" ON public.room_message_reads;
CREATE POLICY "room_reads_insert_own" ON public.room_message_reads FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid());

-- حذف الحساب الحالي نهائيًا
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;
revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;


-- ===== ملفات الصور والرسائل الصوتية =====
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'chat-media',
  'chat-media',
  false,
  12582912,
  array['image/jpeg','image/png','image/webp','image/gif','audio/webm','audio/ogg','audio/mp4','audio/mpeg','audio/aac']
)
on conflict (id) do update set
  public=false,
  file_size_limit=12582912,
  allowed_mime_types=excluded.allowed_mime_types;

DROP POLICY IF EXISTS "chat_media_insert_own" ON storage.objects;
CREATE POLICY "chat_media_insert_own"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id='chat-media'
  AND (storage.foldername(name))[2]=auth.uid()::text
);

DROP POLICY IF EXISTS "chat_media_select_authorized" ON storage.objects;
CREATE POLICY "chat_media_select_authorized"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id='chat-media'
  AND (
    owner_id=auth.uid()::text
    OR EXISTS (
      SELECT 1 FROM public.messages m
      WHERE m.media_path=storage.objects.name
    )
    OR EXISTS (
      SELECT 1 FROM public.private_messages pm
      WHERE pm.media_path=storage.objects.name
        AND (pm.sender_id=auth.uid() OR pm.receiver_id=auth.uid())
    )
  )
);

DROP POLICY IF EXISTS "chat_media_delete_own" ON storage.objects;
CREATE POLICY "chat_media_delete_own"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id='chat-media'
  AND owner_id=auth.uid()::text
);

-- ===== إعدادات التطبيق =====
create table if not exists public.app_settings (
  id integer primary key check (id=1),
  welcome_text text not null default 'أهلاً بك في ZELZAL CHAT ⚡',
  welcome_enabled boolean not null default true,
  music_mode text not null default 'off' check (music_mode in ('off','calm1','calm2','custom')),
  music_url text not null default '',
  music_title text not null default 'موسيقى هادئة',
  updated_at timestamptz not null default now()
);
insert into public.app_settings(id) values(1) on conflict (id) do nothing;

-- ===== RLS =====
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.messages enable row level security;
alter table public.private_messages enable row level security;
alter table public.app_settings enable row level security;

-- profiles
DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_authenticated" ON public.profiles FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id=auth.uid());
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated USING (id=auth.uid()) WITH CHECK (id=auth.uid());
DROP POLICY IF EXISTS "profiles_admin_update" ON public.profiles;
CREATE POLICY "profiles_admin_update" ON public.profiles FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- rooms
DROP POLICY IF EXISTS "rooms_select_authenticated" ON public.rooms;
CREATE POLICY "rooms_select_authenticated" ON public.rooms FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "rooms_insert_authenticated" ON public.rooms;
CREATE POLICY "rooms_insert_authenticated" ON public.rooms FOR INSERT TO authenticated WITH CHECK (created_by=auth.uid());
DROP POLICY IF EXISTS "rooms_update_creator" ON public.rooms;
CREATE POLICY "rooms_update_creator" ON public.rooms FOR UPDATE TO authenticated USING (created_by=auth.uid() OR public.is_admin()) WITH CHECK (created_by=auth.uid() OR public.is_admin());
DROP POLICY IF EXISTS "rooms_delete_creator" ON public.rooms;
CREATE POLICY "rooms_delete_creator" ON public.rooms FOR DELETE TO authenticated USING (created_by=auth.uid() OR public.is_admin());

-- room messages
DROP POLICY IF EXISTS "messages_select_authenticated" ON public.messages;
CREATE POLICY "messages_select_authenticated" ON public.messages FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "messages_insert_own" ON public.messages;
CREATE POLICY "messages_insert_own" ON public.messages FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid());
DROP POLICY IF EXISTS "messages_delete_own" ON public.messages;
CREATE POLICY "messages_delete_own" ON public.messages FOR DELETE TO authenticated USING (user_id=auth.uid() OR public.is_admin());

-- private messages: فقط المرسل والمستلم
DROP POLICY IF EXISTS "private_select_participants" ON public.private_messages;
CREATE POLICY "private_select_participants" ON public.private_messages FOR SELECT TO authenticated USING (sender_id=auth.uid() OR receiver_id=auth.uid());
DROP POLICY IF EXISTS "private_insert_sender" ON public.private_messages;
CREATE POLICY "private_insert_sender" ON public.private_messages FOR INSERT TO authenticated WITH CHECK (sender_id=auth.uid() AND receiver_id<>auth.uid());
DROP POLICY IF EXISTS "private_update_receiver" ON public.private_messages;
CREATE POLICY "private_update_receiver" ON public.private_messages FOR UPDATE TO authenticated USING (receiver_id=auth.uid()) WITH CHECK (receiver_id=auth.uid());
DROP POLICY IF EXISTS "private_delete_sender" ON public.private_messages;
CREATE POLICY "private_delete_sender" ON public.private_messages FOR DELETE TO authenticated USING (sender_id=auth.uid());

-- app settings
DROP POLICY IF EXISTS "settings_select_authenticated" ON public.app_settings;
CREATE POLICY "settings_select_authenticated" ON public.app_settings FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "settings_admin_update" ON public.app_settings;
CREATE POLICY "settings_admin_update" ON public.app_settings FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ===== Realtime =====
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rooms') then
    alter publication supabase_realtime add table public.rooms;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='private_messages') then
    alter publication supabase_realtime add table public.private_messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='app_settings') then
    alter publication supabase_realtime add table public.app_settings;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='room_message_reads') then
    alter publication supabase_realtime add table public.room_message_reads;
  end if;
end $$;

-- ===== اجعل حسابك مديرًا =====
-- بعد أن تنشئ حسابك، غيّر البريد في السطر التالي ثم شغّله مرة واحدة منفصلًا:
-- update public.profiles p set role='admin' from auth.users u where p.id=u.id and u.email='YOUR_EMAIL@example.com';

-- روم أولي إن كان هناك مستخدم واحد على الأقل ولا توجد رومات
insert into public.rooms(name,description,created_by)
select 'العام','الروم العام',p.id from public.profiles p
where not exists(select 1 from public.rooms)
order by p.created_at limit 1;
