/* Taj Al Molook V5 — Supabase auth/profile/admin/code layer */
(() => {
 const cfg=()=>window.TAJ_SUPABASE_KEY && !window.TAJ_SUPABASE_KEY.includes('PUT_YOUR');
 let sb=null, authMode='login', me=null;
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function toast(s){ window.showToast?showToast(s):alert(s); }
 function client(){ if(!cfg()) throw new Error('أضف Publishable key داخل supabase-config.js'); if(!sb) sb=window.supabase.createClient(window.TAJ_SUPABASE_URL,window.TAJ_SUPABASE_KEY); return sb; }
 function guestId(){ let x=localStorage.getItem('taj_guest_v5'); if(!x){x='G-'+crypto.getRandomValues(new Uint32Array(1))[0].toString().slice(0,7);localStorage.setItem('taj_guest_v5',x)} return x; }
 function badgeGuest(){const b=$('guestBadge');if(b)b.innerHTML=`<span class="status-dot"></span><i class="fa-solid fa-crown text-gold"></i><span>زائر • ${guestId()}</span>`;}
 function badgeUser(p){const b=$('guestBadge');if(b)b.innerHTML=`<span class="status-dot"></span><i class="fa-solid fa-crown text-gold"></i><span>${esc(p.display_name||'حساب')}</span>`;}
 function profileHtml(p){return `<div class="v5-profile"><h3>👑 ${esc(p.display_name)}</h3><div><b>ID</b><span>${esc(p.public_id)}</span></div><div><b>البريد</b><span>${esc(p.email)}</span></div><div><b>حالة الكود</b><span>${esc(p.code_status||'لا يوجد')}</span></div><div><b>تاريخ الانضمام</b><span>${new Date(p.created_at).toLocaleString('ar-IQ')}</span></div><div><b>حالة الحساب</b><span>${p.account_status==='active'?'مفعّل':esc(p.account_status)}</span></div><button class="btn btn-glass w-100" onclick="tajV5.logout()">تسجيل خروج</button></div>`}
 async function loadMe(){ const c=client(),{data:{user}}=await c.auth.getUser(); if(!user){me=null;badgeGuest();return null} const {data,error}=await c.from('profiles').select('*').eq('id',user.id).single(); if(error) throw error; me=data; badgeUser(me); if(me.account_status==='banned') toast('هذا الحساب محظور من الإدارة'); return me; }
 async function showAccount(){try{const p=await loadMe();if(!p){openSection('login');return} let box=$('v5AccountBox'); if(!box){box=document.createElement('div');box.id='v5AccountBox';box.className='v5-overlay';document.body.appendChild(box)} box.innerHTML=`<div class="v5-dialog"><button class="v5-x" onclick="this.closest('.v5-overlay').remove()">×</button>${profileHtml(p)}</div>`;}catch(e){toast(e.message)}}
 window.switchAuthTab=function(mode){authMode=mode; $('tabLogin')?.classList.toggle('active',mode==='login');$('tabRegister')?.classList.toggle('active',mode==='register');if($('groupName'))$('groupName').style.display=mode==='register'?'block':'none';if($('authBtnText'))$('authBtnText').textContent=mode==='login'?'دخول الحساب':'إنشاء الحساب';};
 window.handleAuthSubmit=async function(e){e.preventDefault();try{const c=client(),email=$('authEmail').value.trim(),password=$('authPass').value,name=$('authName')?.value.trim(); if(authMode==='register'){if(!name)throw new Error('اكتب اسم الحساب');const {error}=await c.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;toast('تم إنشاء الحساب. إذا كان تأكيد البريد مفعّلًا، افتح رسالة التأكيد ثم سجل الدخول.');switchAuthTab('login');}else{const {error}=await c.auth.signInWithPassword({email,password});if(error)throw error;await loadMe();toast('تم تسجيل الدخول');closeSection();}}catch(x){toast(x.message)}};
 async function logout(){try{await client().auth.signOut();me=null;badgeGuest();document.querySelector('.v5-overlay')?.remove();toast('تم تسجيل الخروج')}catch(e){toast(e.message)}}
 async function activateCode(){try{const p=await loadMe();if(!p)throw new Error('سجل الدخول أولاً لتفعيل الكود');const input=$('activationCode');const code=input?.value.trim().toUpperCase();if(!code)throw new Error('أدخل الكود');const {data,error}=await client().rpc('activate_subscription_code',{p_code:code});if(error)throw error;toast(data.message||'تم التفعيل');await loadMe();window.tajV5.renderCode();}catch(e){toast(e.message)}}
 async function renderCode(){const box=$('activationResult');if(!box)return;try{const p=await loadMe();if(!p){box.classList.remove('hidden');box.innerHTML='سجّل الدخول لعرض حالة الكود.';return}const {data}=await client().from('my_subscription').select('*').maybeSingle();box.classList.remove('hidden');if(!data){box.innerHTML='لا يوجد كود مفعّل.';return}const end=new Date(data.expires_at),active=end>Date.now();box.innerHTML=`<div class="code-status-card ${active?'is-active':'is-expired'}"><strong>${active?'🟢 مفعّل':'🔴 منتهي'}</strong><p>${esc(data.code_type)} • ${esc(data.code)}</p><p>ينتهي: ${end.toLocaleString('ar-IQ')}</p></div>`;}catch(e){box.innerHTML=esc(e.message)}}
 async function admin(){try{const p=await loadMe();if(!p||p.role!=='admin')throw new Error('هذه الواجهة للمطور فقط');const c=client();const [{data:users},{data:guests},{data:codes},{data:msgs}]=await Promise.all([c.from('profiles').select('id,public_id,display_name,email,account_status,created_at').order('created_at',{ascending:false}).limit(100),c.from('guest_sessions').select('*').order('last_seen',{ascending:false}).limit(100),c.from('subscription_codes').select('*').order('created_at',{ascending:false}).limit(100),c.from('support_messages').select('*').order('created_at',{ascending:false}).limit(100)]);let o=$('v5Admin');if(!o){o=document.createElement('div');o.id='v5Admin';o.className='v5-overlay';document.body.appendChild(o)}o.innerHTML=`<div class="v5-admin"><button class="v5-x" onclick="this.closest('.v5-overlay').remove()">×</button><h2>لوحة المطور 👑</h2><div class="v5-admin-grid"><section><h3>توليد كود</h3><select id="admType"><option value="trial">تجريبي</option><option value="basic">أساسي</option></select><select id="admDur"><option value="60">ساعة</option><option value="1440">يوم</option><option value="10080">أسبوع</option><option value="43200">شهر</option><option value="259200">6 أشهر</option></select><button class="btn btn-gold-neon" onclick="tajV5.genCode()">توليد</button><div id="admNewCode"></div></section><section><h3>المستخدمون (${users?.length||0})</h3>${(users||[]).map(u=>`<div class="adm-row"><span>${esc(u.display_name)}<small>${esc(u.public_id)} • ${esc(u.account_status)}</small></span><button onclick="tajV5.setStatus('${u.id}','restricted')">تقييد</button><button onclick="tajV5.setStatus('${u.id}','banned')">حظر</button><button onclick="tajV5.setStatus('${u.id}','active')">فك</button></div>`).join('')}</section><section><h3>الزوار (${guests?.length||0})</h3>${(guests||[]).map(g=>`<div class="adm-row"><span>${esc(g.guest_id)}<small>${new Date(g.last_seen).toLocaleString('ar-IQ')}</small></span></div>`).join('')}</section><section><h3>الأكواد (${codes?.length||0})</h3>${(codes||[]).map(k=>`<div class="adm-row"><span>${esc(k.code)}<small>${esc(k.code_type)} • ${k.duration_minutes} دقيقة • ${k.used_by?'مستخدم':'متاح'}</small></span></div>`).join('')}</section><section><h3>رسائل الدعم (${msgs?.length||0})</h3>${(msgs||[]).map(m=>`<div class="adm-msg"><b>${esc(m.sender_name||m.guest_id||'مستخدم')}</b><p>${esc(m.body)}</p></div>`).join('')}</section></div></div>`;}catch(e){toast(e.message)}}
 async function genCode(){try{const {data,error}=await client().rpc('admin_generate_code',{p_type:$('admType').value,p_duration_minutes:Number($('admDur').value)});if(error)throw error;$('admNewCode').textContent='الكود: '+data;toast('تم توليد الكود')}catch(e){toast(e.message)}}
 async function setStatus(id,status){try{const {error}=await client().rpc('admin_set_account_status',{p_user:id,p_status:status});if(error)throw error;toast('تم تحديث الحساب');admin()}catch(e){toast(e.message)}}
 async function support(body){try{const p=await loadMe();const {error}=await client().from('support_messages').insert({user_id:p?.id||null,guest_id:p?null:guestId(),sender_name:p?.display_name||'زائر',body});if(error)throw error;toast('تم إرسال رسالتك إلى المطور')}catch(e){toast(e.message)}}
 async function trackGuest(){if(!cfg())return;try{const c=client();await c.from('guest_sessions').upsert({guest_id:guestId(),last_seen:new Date().toISOString()},{onConflict:'guest_id'});}catch{}}
 window.tajV5={loadMe,showAccount,logout,activateCode,renderCode,admin,genCode,setStatus,support};
 document.addEventListener('DOMContentLoaded',async()=>{badgeGuest();if(cfg()){try{await loadMe();await trackGuest();client().auth.onAuthStateChange(()=>setTimeout(loadMe,0));}catch(e){console.warn(e)}} const b=$('guestBadge');if(b)b.onclick=()=>me?showAccount():openSection('login'); const old=window.activateCode;if($('activationCode'))window.activateCode=activateCode;});
})();
