/* Taj Al Molook V6 — points wallet + code shop */
(()=>{
 let sb=null, me=null;
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const toast=s=>window.showToast?showToast(s):alert(s);
 function ready(){return window.TAJ_SUPABASE_KEY&&!window.TAJ_SUPABASE_KEY.includes('PUT_YOUR')}
 function client(){if(!ready())throw Error('أضف Publishable key داخل supabase-config.js');return sb||(sb=window.supabase.createClient(window.TAJ_SUPABASE_URL,window.TAJ_SUPABASE_KEY))}
 async function load(){const {data:{user}}=await client().auth.getUser();if(!user){me=null;return null}const {data,error}=await client().from('profiles').select('*').eq('id',user.id).single();if(error)throw error;me=data;renderPoints();return me}
 function renderPoints(){document.querySelectorAll('.v6-points').forEach(x=>x.textContent=Number(me?.points||0).toLocaleString('ar-IQ')+' نقطة')}
 function duration(m){if(m%43200===0)return (m/43200)+' شهر';if(m%10080===0)return (m/10080)+' أسبوع';if(m%1440===0)return (m/1440)+' يوم';if(m%60===0)return (m/60)+' ساعة';return m+' دقيقة'}
 async function shop(){try{const p=await load();const host=document.querySelector('#view-buy-code .view-body');if(!host)return;if(!p){host.innerHTML='<div class="v6-empty">سجّل الدخول أولاً لشراء الأكواد بالنقاط.</div>';return}const {data,error}=await client().from('code_products').select('*').eq('enabled',true).order('points_price');if(error)throw error;host.innerHTML=`<div class="v6-wallet"><span>رصيدك</span><strong class="v6-points">${Number(p.points||0).toLocaleString('ar-IQ')} نقطة</strong></div><div class="v6-shop-title"><h3>متجر الأكواد بالنقاط</h3><p>اختر البطاقة المناسبة. يتم التحقق من السعر والرصيد داخل Supabase.</p></div><div class="v6-products">${(data||[]).length?(data||[]).map(x=>`<article class="v6-product"><div class="v6-product-icon">👑</div><h3>${esc(x.title)}</h3><span class="v6-type ${x.code_type}">${x.code_type==='trial'?'تجريبي':'أساسي'}</span><p>المدة: <b>${duration(x.duration_minutes)}</b></p><div class="v6-price">🪙 ${Number(x.points_price).toLocaleString('ar-IQ')} نقطة</div><button onclick="tajV6.buy('${x.id}')">شراء الكود</button></article>`).join(''):'<div class="v6-empty">لا توجد بطاقات متاحة حاليًا.</div>'}</div><div id="v6Purchased"></div>`}catch(e){toast(e.message)}}
 async function buy(id){try{const {data,error}=await client().rpc('buy_code_product',{p_product:id});if(error)throw error;if(!data?.ok){toast(data?.message||'تعذر الشراء');return}await load();const box=$('v6Purchased');if(box)box.innerHTML=`<div class="v6-bought"><b>✅ تم شراء الكود</b><code>${esc(data.code)}</code><span>${data.code_type==='trial'?'تجريبي':'أساسي'} • ${duration(data.duration_minutes)}</span><button onclick="navigator.clipboard.writeText('${esc(data.code)}');showToast('تم نسخ الكود')">نسخ الكود</button></div>`;renderPoints();toast('تم شراء الكود بنجاح')}catch(e){toast(e.message)}}
 function patchProfile(){const old=window.tajV5?.showAccount;if(!old)return;window.tajV5.showAccount=async()=>{await old();try{await load();const prof=document.querySelector('.v5-profile');if(prof&&!prof.querySelector('.v6-wallet-row')){const row=document.createElement('div');row.className='v6-wallet-row';row.innerHTML=`<b>النقاط</b><span class="v6-points">${Number(me?.points||0).toLocaleString('ar-IQ')} نقطة</span>`;const first=prof.querySelector('div');first?first.before(row):prof.appendChild(row)}}catch{}}}
 async function enhanceAdmin(){try{const p=await load();if(!p||p.role!=='admin')return;setTimeout(async()=>{const root=document.querySelector('.v5-admin-grid');if(!root||root.querySelector('#v6AdminShop'))return;const {data:products}=await client().from('code_products').select('*').order('created_at',{ascending:false});const s=document.createElement('section');s.id='v6AdminShop';s.innerHTML=`<h3>متجر النقاط</h3><input id="v6ProdTitle" placeholder="اسم البطاقة"><select id="v6ProdType"><option value="trial">تجريبي</option><option value="basic">أساسي</option></select><select id="v6ProdDur"><option value="60">ساعة</option><option value="1440">يوم</option><option value="10080">أسبوع</option><option value="43200">شهر</option><option value="259200">6 أشهر</option></select><input id="v6ProdPrice" type="number" min="0" placeholder="النقاط المطلوبة"><button onclick="tajV6.createProduct()">إضافة البطاقة</button><div>${(products||[]).map(x=>`<div class="adm-row"><span>${esc(x.title)}<small>${duration(x.duration_minutes)} • ${Number(x.points_price).toLocaleString()} نقطة • ${x.enabled?'ظاهر':'مخفي'}</small></span><button onclick="tajV6.toggleProduct('${x.id}',${!x.enabled})">${x.enabled?'إخفاء':'إظهار'}</button></div>`).join('')}</div>`;root.prepend(s);document.querySelectorAll('.v5-admin .adm-row').forEach(r=>{const b=r.querySelector("button[onclick*='setStatus']");if(b&&!r.querySelector('.v6-addpts')){const id=(b.getAttribute('onclick').match(/'([^']+)'/)||[])[1];if(id){const q=document.createElement('button');q.className='v6-addpts';q.textContent='نقاط';q.onclick=()=>adjustPrompt(id);r.appendChild(q)}}})},100)}catch(e){console.warn(e)}}
 async function createProduct(){try{const title=$('v6ProdTitle').value.trim(),type=$('v6ProdType').value,dur=+$('v6ProdDur').value,price=+$('v6ProdPrice').value;if(!title||price<0)throw Error('أكمل بيانات البطاقة');const {error}=await client().rpc('admin_create_code_product',{p_title:title,p_type:type,p_duration_minutes:dur,p_points_price:price});if(error)throw error;toast('تمت إضافة البطاقة');document.querySelector('#v5Admin')?.remove();window.tajV5.admin();setTimeout(enhanceAdmin,200)}catch(e){toast(e.message)}}
 async function toggleProduct(id,on){try{const {error}=await client().rpc('admin_set_product_enabled',{p_product:id,p_enabled:on});if(error)throw error;toast('تم تحديث البطاقة');document.querySelector('#v5Admin')?.remove();window.tajV5.admin();setTimeout(enhanceAdmin,200)}catch(e){toast(e.message)}}
 function adjustPrompt(id){const amount=prompt('أدخل النقاط: موجب للإضافة، سالب للخصم');if(amount===null)return;const n=Number(amount);if(!Number.isInteger(n)||n===0)return toast('أدخل رقمًا صحيحًا');adjust(id,n)}
 async function adjust(id,n){try{const {data,error}=await client().rpc('admin_adjust_points',{p_user:id,p_amount:n,p_note:'تعديل من لوحة المطور'});if(error)throw error;toast('الرصيد الجديد: '+Number(data).toLocaleString('ar-IQ')+' نقطة')}catch(e){toast(e.message)}}
 document.addEventListener('DOMContentLoaded',()=>{if(!ready())return;setTimeout(()=>{patchProfile();const oldOpen=window.openSection;window.openSection=function(name){const r=oldOpen.apply(this,arguments);if(name==='buy-code')setTimeout(shop,50);return r};if(window.tajV5?.admin){const oa=window.tajV5.admin;window.tajV5.admin=async()=>{await oa();enhanceAdmin()}};load().catch(()=>{})},150)});
 window.tajV6={shop,buy,createProduct,toggleProduct,adjust};
})();
